# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Lorum Isoum'),
            preserve_default=False,
        ),
    ]
